### ISSUE TITLE
[Feature Request] add Mock panel in web console

### ISSUE THREAD

**Issue by loveky** [jdf2e/rocketact#10]
在 web console 中增加 Mock 功能（名称待定）

主要支持以下场景：

- [x] 支持将特定url映射到本地json文件
- [x] 支持按照规则将接口转发到远程服务器
- [ ] 支持对接成熟的第三方服务，比如 swagger

其它功能：

- [x] 实时保存配置信息到项目目录，方便多人共享
- [x] 允许用户在web console 中对规则排序
- [x] 允许用户在web console 开启或停用某条规则

cc @beanlee  看看还有什么场景或注意事项

**Comment by beanlee** [comment]
赞，暂时没想到其他，可以考虑把这些功能完成后，同时放在 web console 的侧边栏菜单内，使用 web 界面来配置

**Comment by loveky** [comment]
经测试swagger服务也可以通过 接口转发 实现
