### ISSUE TITLE
[Feature Request] 支持 yarn --pnp

### ISSUE THREAD

**Issue by beanlee** [jdf2e/rocketact#16]
**Is your feature request related to a problem? Please describe.**
当前项目使用 `yarn --pnp` 安装依赖时，无法支持 `rocketact-plugin-xxx`

**Describe the solution you'd like**
调整扫描插件的实现，支持 `pnp`

**Describe alternatives you've considered**
获取可以通过你今天分享提到 `pnp` 的API来获取插件的实际地址来 require

packages/rocketact-scripts
```ts 
resolveInstalledPlugins() {
    const installedPlugins = Object.keys(this.pkg.dependencies || {})
      .filter(isPlugin)
      .concat(Object.keys(this.pkg.devDependencies || {}).filter(isPlugin));
    installedPlugins.forEach(plugin =>
      require(resolveToAppRoot(`./node_modules/${plugin}`))(new CoreAPI(this))
    );
  }
```

**Comment by loveky** [comment]
Will investigate on this in next few days

**Comment by loveky** [comment]
Yarn PnP support has been add in b02b04afb0c392f6d3c5e15ba10431bcfc6d08d7 

**Known issue**: Tsc currently do not support PnP(see https://github.com/Microsoft/TypeScript/issues/28289). That means if we enable PnP in a TS project (not only Roecketact projects), the TS engine cannot find the type file which installed as `@types/xxx` packages and leads to a bunch of type errors/warnings. That means currently PnP can only be enabled in JavaScript projects.

**Comment by beanlee** [comment]
Okay
