### ISSUE TITLE
[Feature Request] optimize tslint conifig

### ISSUE THREAD

**Issue by loveky** [jdf2e/rocketact#17]
优化tslint配置

**Comment by loveky** [comment]
possible candidate：

- tslint:latest
- tslint:recommended
- tslint-react
- [tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib)
- tslint-config-airbnb

will give them a try and come back later

**Comment by loveky** [comment]
cc @beanlee @hanyuxinting  可以都体验一下，看看哪个合适

**Comment by beanlee** [comment]
看到微软，决定 try 一 try
