### ISSUE TITLE
[Feature Request] 能支持decorator的老版本么

### ISSUE THREAD

**Issue by hanyuxinting** [jdf2e/rocketact#28]
# 🌈 Feature

目前遇到了一个问题，在使用Mobx时，不支持修饰符，提示：

Support for the experimental syntax 'decorators-legacy' isn't currently enabled

修改 tsconfig.json 的 experimentalDecorators 选项，也没有搞定。

经了解，rocketact 是通过babel编译的，目前使用的是decorator的新版本，能否实现老版本呢？

非常感谢~

**Comment by loveky** [comment]
升级 rocketact-scripts 至 1.8.2，并安装 rocketact-plugin-legacy-decorators >= 1.0.2 版本即可

**Comment by hanyuxinting** [comment]
well done,tks~~
