### ISSUE TITLE
引入 lottie-react-web 包后build 后页面报错

### ISSUE THREAD

**Issue by caifeng** [jdf2e/rocketact#29]
# ❔ 引入 lottie-react-web包 build后 预览页面报错

![企业咚咚20190509095210](https://user-images.githubusercontent.com/1281595/57421866-283bec80-7240-11e9-9201-35f5cd1882d7.png)

**Comment by loveky** [comment]
Submitted https://github.com/mishoo/UglifyJS2/issues/3400 to UglifyJS.

**Comment by loveky** [comment]
temporarily disabled `reduce_funcs` option for UglifyJS
