### ISSUE TITLE
[Feature Request] consider switch from  uglifyJS to Terser

### ISSUE THREAD

**Issue by loveky** [jdf2e/rocketact#31]
# 🌈 Feature

- [webpack@5 will use terser plugin by default.](https://github.com/webpack-contrib/terser-webpack-plugin/issues/15#issuecomment-421388132)

**Comment by beanlee** [comment]
竟然看到这个issue，少年，我还单独提了一个 #40 这个应该可以关闭了

``terser ``稳定性只有靠我手上的项目来验证了
