### ISSUE TITLE
[讨论] ProxyConfig 当时为什么在保存时去除了 enable ？以及设置 enable 时为什么没有同步保存到本地？

### ISSUE THREAD

**Issue by beanlee** [jdf2e/rocketact#45]
疑问？

有一个需求，当项目配置 n 个接口代理，亟需一个一键生效所有代理的功能，否则每次启动以后都要手动一个一个点开，但其实看代码 API 内部在写入文件的时候只是过滤掉了这个属性，原本是保存某一个或某一些接口代理状态的功能。

当时为什么在保存时去除了 enabled ？

保存时过滤掉 enabled 属性，保证用户每次启动项目都默认不开启，以免造成困扰吗？

针对这个问题有两个想法：

* 同步保存 enabled 属性
* 保存时过滤逻辑保留，提供 enable all 和 disable all 两个按钮

https://github.com/jdf2e/rocketact/blob/1c70398938d1a69ebf2037e29508380a9ee7d6f5/packages/rocketact-web-console/src/server/proxyAPI.ts#L37-L49

这部分代码，设置 enable 时为什么没有同步保存到本地？

https://github.com/jdf2e/rocketact/blob/1c70398938d1a69ebf2037e29508380a9ee7d6f5/packages/rocketact-web-console/src/server/proxyAPI.ts#L99-L111

**Comment by loveky** [comment]
> 保存时过滤掉 enabled 属性，保证用户每次启动项目都默认不开启，以免造成困扰吗？

这块儿当时应该考虑的是如果在本地环境里增加enabled字段，用户有可能在启动开发环境的状态下手动修改配置问题，然而直接修改时开发环境是不会生效的，应该是怕造成困扰(也许这个担心是多余的)

>保存时过滤逻辑保留，提供 enable all 和 disable all 两个按钮

👍 
还可以考虑给start 增加一个参数， --auto-mock

**Comment by beanlee** [comment]
OK，打算加按钮这么搞，不过文档上加一行说明，当前修改代理mock的状态并不会同步保存

**Comment by beanlee** [comment]
![enableall](https://user-images.githubusercontent.com/1539081/80665520-44c5da00-8acc-11ea-808f-da7c4a3743ef.gif)

Tada~

**Comment by loveky** [comment]
👏 👏 👏 👏
