### ISSUE TITLE
[Feature Request] 多页面入口支持 `pages` 下更沉一层文件夹

### ISSUE THREAD

**Issue by beanlee** [jdf2e/rocketact#54]
# 🌈 Feature

多页面入口配置，支持 `pages`  目录下，更沉一层文件夹。

```
.
└── src
    ├── pageA
    │   ├── pageA.html
    │   └── pageA.tsx
    └── pageB
        ├── pageB.html
        └── pageB.tsx
```

现有代码只支持多页面在同一层

https://github.com/jdf2e/rocketact/blob/738981920d29ff61ea7619fa94e447b2653ee131/packages/rocketact-dev-utils/src/getValidEntries.ts#L16-L28

**Comment by loveky** [comment]
![image](https://user-images.githubusercontent.com/1198651/89101660-8ac86c00-d434-11ea-8784-3c4ba9f88626.png)
 pageA在这三个位置是完全一致的吗？

**Comment by beanlee** [comment]
> ![image](https://user-images.githubusercontent.com/1198651/89101660-8ac86c00-d434-11ea-8784-3c4ba9f88626.png)
> pageA在这三个位置是完全一致的吗？

理想情况下是完全一致，但是我觉得如果支持 pages 下面递归寻找入口这个功能的话，那其实使用者很容易会遇到目录和页面名称不一致的问题。

比如
pageA
   -- a.tsx
   -- a.html
xxxxPage
    --y.tsx
    --y.html

**Comment by loveky** [comment]
如果没有什么场景明确有这种诉求的话，建议还是不要搞太复杂，没有太明确的收益。反而增加维护成本

**Comment by beanlee** [comment]
> 如果没有什么场景明确有这种诉求的话，建议还是不要搞太复杂，没有太明确的收益。反而增加维护成本

是的，最一开始我的建议就是 pages 下一级目录即可，通过其他文件夹来管理不同页面的内容，不建议 pages 下过于复杂。

所谓“约定大于配置”的好处吧，我们加强 pages 下的约束，代码上和配置上都不需要过多兼容这种特殊需求。目前我单独提供的 beta0 版本，勉强够用 :D 

主版本就先不添加了，issue 关闭吧
