### ISSUE TITLE
[Feature Request] build 增加 --with-version

### ISSUE THREAD

**Issue by beanlee** [jdf2e/rocketact#55]
# 🌈 Feature

支持将 version 放在构建在引用路径内，以适应不用 `hash` 只使用 `version` 来控制构建产物的场景

理论上 --no-hash 配置平行，互相无影响

**Comment by loveky** [comment]
准备以什么作为version呢

**Comment by beanlee** [comment]
> 准备以什么作为version呢

是 PLUS 业务他们的场景，不用 hash，全用 jdf 那种打包后的路径作为上线产物，我今天想了想直接做成一个插件，不用小火箭本身提供该功能。

[https://www.npmjs.com/package/rocketact-plugin-bundle-with-version](https://www.npmjs.com/package/rocketact-plugin-bundle-with-version)

另外还写了一个 他们要用的 banner plugin 的，都差不多

[https://www.npmjs.com/package/rocketact-plugin-bundle-with-banner](https://www.npmjs.com/package/rocketact-plugin-bundle-with-banner)

**Comment by beanlee** [comment]
> 准备以什么作为version呢

就以 `package.json` 中的 `version` 字段打包，bundle 时追加在 publicPath 后。

**Comment by loveky** [comment]
> > 准备以什么作为version呢
> 
> 就以 `package.json` 中的 `version` 字段打包，bundle 时追加在 publicPath 后。

然后把文件名中的hash去掉么？怎么保证 manifest,vendor和app 三个js的一致性呢，

**Comment by beanlee** [comment]
> > > 准备以什么作为version呢
> > 
> > 
> > 就以 `package.json` 中的 `version` 字段打包，bundle 时追加在 publicPath 后。
> 
> 然后把文件名中的hash去掉么？怎么保证 manifest,vendor和app 三个js的一致性呢，

哈哈，不用保证 manifest, verdor, app 的一致性，他们的需求是每次都更新版本号，打包出来的新版本路径下文件全量上线。

**Comment by beanlee** [comment]
通过插件解决 [https://www.npmjs.com/package/rocketact-plugin-bundle-with-version](https://www.npmjs.com/package/rocketact-plugin-bundle-with-version)
