### ISSUE TITLE
[Feature Request] react-refresh support 

### ISSUE THREAD

**Issue by zhhyang** [jdf2e/rocketact#87]
嘿，大佬，支持一下 react-refresh 么

**Comment by beanlee** [comment]
本来是有计划想搞的，和 cra 一样的支持 fast-refresh

**Comment by zhhyang** [comment]
我先临时搞个plugin支持一下，等官方支持了就删掉

**Comment by zhhyang** [comment]
see [rocketact-plugin-react-refresh](https://www.npmjs.com/package/rocketact-plugin-react-refresh)
